// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
// - LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';

//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
